services:
  - type: web
    name: kafka-api-server
    env: node
    plan: free
    buildCommand: cd api-server && npm install
    startCommand: node index.js
    envVars:
      - key: KAFKA_BROKER
        value: pkc-921jm.us-east-2.aws.confluent.cloud:9092
      - key: KAFKA_USERNAME
        value: QE7BTXQZWWHK6SSQ
      - key: KAFKA_PASSWORD
        value: 1ETqd7zm/e5cq7uA0GeTvQaRmHLH5h6G80u8UqoUh4MVvwPevNdpuG5Gi8Xib0x/
      - key: TOPIC_NAME
        value: driver-location
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN

  - type: web
    name: kafka-consumer
    env: node
    plan: free
    buildCommand: cd consumer && npm install
    startCommand: node index.js
    envVars:
      - key: KAFKA_BROKER
        value: pkc-921jm.us-east-2.aws.confluent.cloud:9092
      - key: KAFKA_USERNAME
        value: QE7BTXQZWWHK6SSQ
      - key: KAFKA_PASSWORD
        value: 1ETqd7zm/e5cq7uA0GeTvQaRmHLH5h6G80u8UqoUh4MVvwPevNdpuG5Gi8Xib0x/
      - key: TOPIC_NAME
        value: driver-location
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN

  - type: web
    name: kafka-producer
    env: node
    plan: free
    buildCommand: cd producer && npm install
    startCommand: node index.js
    envVars:
      - key: KAFKA_BROKER
        value: pkc-921jm.us-east-2.aws.confluent.cloud:9092
      - key: KAFKA_USERNAME
        value: QE7BTXQZWWHK6SSQ
      - key: KAFKA_PASSWORD
        value: 1ETqd7zm/e5cq7uA0GeTvQaRmHLH5h6G80u8UqoUh4MVvwPevNdpuG5Gi8Xib0x/
      - key: TOPIC_NAME
        value: driver-location
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN

  - type: web
    name: kafka-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port $PORT
